version: '3'
services:
  python:
    build: .
    environment:
      - PORT=${PORT}
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/sa.json
      - SLACK_API_TOKEN=${SLACK_API_TOKEN}
      - VERIFICATION_TOKEN=${VERIFICATION_TOKEN}
      - STAGE_SERVICE_ACCOUNT_KEY=${STAGE_SERVICE_ACCOUNT_KEY}
      - STAGE_IAP_CLIENT_ID=${STAGE_IAP_CLIENT_ID}
      - STAGE_IAP_REQUEST_URL=${STAGE_IAP_REQUEST_URL}
      - PROD_SERVICE_ACCOUNT_KEY=${PROD_SERVICE_ACCOUNT_KEY}
      - PROD_IAP_CLIENT_ID=${PROD_IAP_CLIENT_ID}
      - PROD_IAP_REQUEST_URL=${PROD_IAP_REQUEST_URL}

    ports:
      - "80:${PORT}"
    volumes:
      - ./app:/app
      - ./service_account:/tmp/keys:ro
